# file = open("file.txt", encoding="utf-8")
# data = file.read()
# # print(data)
# file.close()
# file = open("file.txt", encoding="utf-8")
# data = file.readlines()
# # print(data)
# file.close()
# file = open("file.txt", encoding="utf-8")
# lst = []
# for line in file:
#     lst.append(int(line))
# print(sum(lst))
# # print(data)
# file.close()
# file = open("file.txt","w", encoding="utf-8")
# file.write("Hello, world!")
# file.close()
# file = open("file.txt","a", encoding="utf-8")
# file.write("\nHello, world!")
# file.close()
# file = open("file.txt","r", encoding="utf-8")